version: '3.9'

services:
  mycontainer:
    build: .
    volumes:
      # Mount the local "volume" folder into the container
      - './volume:/home/mpiuser/volume'
    tty: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
